name: Release PDF

on:
  pull_request:
    branches: [main]
    paths: [docs/README.pdf]
  workflow_dispatch:

jobs:
  release:
    name: Release PDF
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: over-sh/setup-bun
        uses: oven-sh/setup-bun@v2 # v2
      - name: bun install
        run: bun install --no-save
      - name: bun build:pdf
        run: bun build:pdf
      - name: create draft release
        uses: softprops/action-gh-release@v2 # v2
        with:
          body: ${{ github.event.pull_request.title }}
          draft: true
          fail_on_unmatched_files: true
          files: docs/README.pdf
          name: Release ${{ github.ref }}